# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message.message_pb2 as message__pb2


class SearchServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Search = channel.unary_unary(
        '/message.SearchService/Search',
        request_serializer=message__pb2.SearchRequest.SerializeToString,
        response_deserializer=message__pb2.Response.FromString,
        )


class SearchServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=message__pb2.SearchRequest.FromString,
          response_serializer=message__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'message.SearchService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
